// Explanations shown by the "?" badges.
export const HELP = {
  target: 'Die Adresse, deren Erreichbarkeit überwacht wird, z. B. 1.1.1.1 oder ein eigener Server. Die App ermittelt per Traceroute den Weg dorthin und teilt ihn in drei Zonen ein.',
  start: 'Startet die Messung: jede Sekunde ein Ping an den Messpunkt jeder Zone, an angehakte Hops und an manuelle Messpunkte. Alles wird gespeichert – auch nach dem Beenden bleibt es unter „Verlauf & Berichte“.',
  LAN: 'Ihr Heimnetz: der letzte eigene Router vor dem Anbieter. Fällt hier etwas aus, liegt die Ursache bei Ihnen (Router, WLAN, Kabel) – nicht beim Anbieter.',
  ISP_EDGE: 'Der erste Knoten Ihres Internetanbieters (Anschluss/„letzte Meile“). Antwortet Ihr Router, dieser Knoten aber nicht mehr, liegt das Problem beim Anbieter.',
  WAN: 'Das eingegebene Ziel im Internet. Ist nur das Ziel weg, aber Ausweichziele (manuelle Messpunkte in Zone WAN) erreichbar, liegt es am Ziel und nicht an Ihrem Anschluss.',
  p50: 'P50 (Median): die typische Antwortzeit – die Hälfte aller Messungen war schneller, die Hälfte langsamer.',
  loss: 'Anteil der Pings ohne Antwort an diesem Messpunkt. Achtung: Router beantworten Pings oft nur mit niedriger Priorität – Verluste an einem Zwischen-Hop sind häufig harmlos, siehe „davon echt“.',
  realLoss: 'Nur Verluste, bei denen auch alle folgenden Messpunkte bis zum Ziel nicht antworteten – also echte Unterbrechungen. Der Rest ist ICMP-Drosselung dieses Routers und beeinträchtigt die Verbindung nicht.',
  jitter: 'Jitter nach RFC 3550: wie stark die Antwortzeit von Ping zu Ping schwankt. Wichtig für Telefonie, Videokonferenzen und Spiele; Werte unter ca. 5 ms sind gut.',
  p9599: 'P95/P99: 95 % bzw. 99 % aller Messungen waren schneller als dieser Wert. Zeigt, wie schlimm die langsamsten Momente sind, ohne dass einzelne Ausreißer alles verzerren.',
  minmax: 'Schnellste und langsamste Antwort der Messung.',
  chart: 'Antwortzeit jedes Messpunkts über die Zeit. Ziehen = Zoom, Doppelklick = zurück, Maus über dem Diagramm = Anzeige hält an. Linien über die Legende oder die Häkchen in der Route-Tabelle ein-/ausblenden. Farbige Flächen = Störungen.',
  diagnosis: 'Automatische Einschätzung aus allen Störungen: Wo beginnt das Problem (Heimnetz, Anbieter oder Ziel)? „Sicherheit“ sagt, wie eindeutig die Messdaten sind – mehr Messzeit und mehr Störungen machen sie sicherer.',
  incidents: 'Eine Störung beginnt, sobald das Ziel, ein Ausweichziel oder ein gewerteter manueller Messpunkt nicht antwortet. Die Matrix zeigt jede Sekunde für jeden Messpunkt: grün = antwortet, orange = langsam, rot = keine Antwort, lila gestreift = möglicher Fehlalarm (Ping weg, aber TCP zum selben Host ok oder umgekehrt – zählt als erreichbar). Blasse Spalten zeigen 10 s davor und 5 s danach zum Vergleich.',
  events: 'Chronologisches Protokoll: Start/Ende, Routenwechsel, Verluste (mit dem Hop, ab dem nichts mehr antwortete), Latenzspitzen, Ausfälle und Messpunkte ohne Antwort. „Harmlos“ = nur ein Zwischen-Hop schwieg, das Ziel antwortete.',
  route: 'Der aktuelle Weg zum Ziel (Traceroute), Hop für Hop. Wird alle 5 Minuten und bei Ausfällen neu geprüft; Änderungen stehen im Ereignisprotokoll.',
  ttl: 'Position auf dem Weg: 1 = erster Router (meist Ihr eigener), jede weitere Zahl ein Router weiter Richtung Ziel.',
  addr: 'IP-Adresse des Routers. „*“ = dieser Router beantwortet keine Pings – das ist normal und kein Fehler.',
  name: 'Eigener Name für den Hop (z. B. „Fritz!Box“). Wird pro Adresse gespeichert und in Legende, Protokoll und Bericht verwendet.',
  zone: 'Zu welchem Bereich der Hop gehört. „Auto“ = automatische Einteilung. Ändern Sie die Zone, wenn die Einteilung nicht stimmt; die Wahl wird pro Adresse gemerkt.',
  rtt: 'Antwortzeit beim Ermitteln der Route.',
  diagram: 'Zeigt den Hop als eigene Linie im Diagramm. Bei Zonen-Messpunkten wird nur ein-/ausgeblendet; andere Hops werden nur gemessen, solange das Häkchen gesetzt ist.',
  custom: 'Vorgeschlagen sind 1.1.1.1 (Cloudflare), 9.9.9.9 (Quad9) und 8.8.8.8 (Google) als Ausweichziele – einfach per Schalter aktivieren. Zusätzliche Geräte oder Server, die jede Sekunde angepingt werden – z. B. ein zweiter Router, NAS oder Ausweichziele wie 1.1.1.1 oder ein eigener VPS.',
  customZone: 'Bestimmt, wie der Messpunkt in die Auswertung eingeht:\nLAN / ISP_EDGE: zählt zu diesem Bereich – fällt er zusammen mit allen Zielen aus, wird die Störung diesem Bereich zugeordnet.\nWAN: Ausweichziel – ist nur das Hauptziel weg, dieses aber erreichbar, liegt es am Ziel.\nkeine: wird nur gemessen und angezeigt, aber nicht gewertet.',
  tcp: 'Prüft zusätzlich jede Sekunde, ob ein TCP-Verbindungsaufbau zum angegebenen Port gelingt (Standard 443 = HTTPS), und misst dessen Dauer (≈ eine Round-Trip-Zeit). Das entspricht echtem Web-Traffic – sinnvoll, weil viele Anbieter/Server Pings nur nachrangig behandeln oder drosseln. Schalter = TCP-Check an/aus, Häkchen = Linie im Diagramm ein-/ausblenden. Erscheint als eigene, gepunktete Linie im Diagramm und als eigene Zeile in der Störungs-Matrix; zählt in derselben Zone wie der Messpunkt. Eine abgelehnte Verbindung (Port zu) gilt als erreichbar.',
  pingSwitch: 'Schalter = Ping an diesen Host messen (an/aus, ausgeschaltet wird gar nicht gemessen und nicht gewertet). Häkchen mit Farbpunkt = Linie im Diagramm ein-/ausblenden – die Messung läuft dabei weiter.',
  note: 'Freitext zu dieser Messung, z. B. Messaufbau (LAN/WLAN), Änderungen (Router getauscht, Techniker war da) oder Tageszeit. Hilft, mehrere Messungen später miteinander zu vergleichen. Erscheint in der Sitzungsliste und im HTML-Bericht.',
  netinfo: 'Beim Start jeder Messung automatisch festgehalten: lokale IP und Netzwerkadapter, Standard-Gateway, DNS-Server sowie Routing- und ARP-Tabelle. So ist dokumentiert, über welchen Weg gemessen wurde (z. B. direkt an der Fritz!Box oder hinter der Firewall), und mehrere Berichte lassen sich vergleichen.',
  customAuto: 'Auto: private Adressen (z. B. 192.168.x.x) → LAN, alle anderen → WAN.',
  sessions: 'Alle gespeicherten Messungen. Laufende Messungen erscheinen hier ebenfalls.',
  exportHtml: 'Vollständiger Bericht mit Diagnose, Kennzahlen, Störungs-Matrix, Ereignisprotokoll und Route. Im Browser öffnen und über „Drucken → Als PDF speichern“ als PDF weitergeben.',
  exportCsv: 'Alle Einzelmessungen (Zeit, Messpunkt, Antwortzeit, Verlust) zur eigenen Auswertung, z. B. in Excel.',
  exportEvents: 'Das Ereignisprotokoll als Tabelle (CSV).',
  spikes: 'Anzahl der Messungen über 100 ms.',
  outageTime: 'Summe der Ausfälle (mindestens 3 Sekunden in Folge keine Antwort bis zum Ziel), die dieser Zone zugeordnet wurden.',
  harmless: 'Verluste nur an einem Zwischen-Hop, während das Ziel antwortete. Entsteht durch ICMP-Drosselung der Router und ist kein Verbindungsproblem.',
}
